name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build index.md
        run: python3 create_index.py
      
      - name: Push index.md
        run: git add . && git commit -m "created index" && git push


