name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build index.md
        run: python3 create_index.py
      
      - name: Push index.md
        run: |
          git config --global user.name 'Deniz Cankurtaran'
          git config --global user.email 'DenizCankurtaran@users.noreply.github.com'
          git add -A
          git commit -m "Automatically created index.md"
          git push